(define (mul a b)
  (define (even n)
    (= (remainder n 2) 0))
  (define (double x)
    (+ x x))  
  (define (halve x)
    (/ x 2))
  (define (fast-mul t a b)
    (cond ((= b 0) t)
      ((even b) (fast-mul t (double a) (halve b)))
      (else (fast-mul (+ t a) a (- b 1)))
    )
  )
  (fast-mul 0 a b)
)

(mul 7 8)